use crate::db::types::UnixTimestamp;
use anyhow::Error;
use once_cell::sync::Lazy;
use sqlx::SqlitePool;
use std::collections::HashMap;
use std::future::Future;
use std::pin::Pin;
use std::sync::Mutex;

type MigrationFn =
    for<'a> fn(&'a SqlitePool) -> Pin<Box<dyn Future<Output = Result<(), Error>> + Send + 'a>>;

static REGISTRY: Lazy<Mutex<HashMap<&'static str, MigrationFn>>> =
    Lazy::new(|| Mutex::new(HashMap::new()));

/// Registers an `async fn` as a Cadmus runtime database migration.
///
/// The macro takes a stable string literal ID and an `async fn` definition.
/// The function is registered into the global migration registry automatically
/// before `main` runs, via `ctor`.
///
/// Migrations can be defined anywhere inside `cadmus-core` — co-locate them
/// with the feature they belong to (e.g. `library/migrations.rs`).
///
/// Doc comments placed before the `async fn` are forwarded onto the generated
/// function and the generated submodule, making them visible in rustdoc.
/// The macro also appends the migration ID and a rerun SQL snippet
/// automatically.
///
/// # Arguments
///
/// * `$id` — Stable string literal identifying this migration in
///   `_cadmus_migrations`. Never change after deployment.
/// * The `async fn` — Must accept `&SqlitePool` and return
///   `Result<(), anyhow::Error>`.
///
/// The generated inner module is named after `$name`, so `$name` must be
/// unique across all `migration!` calls in the crate.
///
/// # Use Cases
///
/// Migrations are one-time operations that run once per deployment. They can:
/// - **Transform data** — backfill metadata, normalize formats, compute derived values
/// - **Import legacy data** — load from filesystem/config into the database
/// - **Cleanup** — prune obsolete rows, remove temporary data, optimize storage
/// - **Any procedural setup** — not limited to SQL; can call filesystem operations,
///   external APIs, or other async code
///
/// **Note:** Schema updates (creating/altering tables) should be handled via `.sql`
/// files in `crates/core/migrations/`, not runtime migrations. SQL migrations are
/// applied by `sqlx-cli` or the `migrate!` macro before runtime migrations run.
///
/// # SQL Best Practices
///
/// When executing SQL in migrations, use SQLx's typed query macros for compile-time
/// verification:
///
/// - Use `sqlx::query!` for `INSERT`, `UPDATE`, `DELETE`, and `SELECT` returning rows
/// - Use `sqlx::query_as!` when mapping results into a named struct
/// - Use `sqlx::query_scalar!` for single-column results
/// - Pass `&mut **tx` (double deref) when executing against a transaction
///
/// # Example
///
/// ```rust
/// mod my_migrations {
///     use sqlx::SqlitePool;
///
///     cadmus_core::migration!(
///         /// Backfills metadata from legacy storage.
///         "v1_backfill_metadata",
///         async fn backfill_metadata(pool: &SqlitePool) {
///             // sqlx::query!(...).execute(pool).await?;
///             Ok(())
///         }
///     );
/// }
/// ```
#[macro_export]
macro_rules! migration {
    ($(#[$attr:meta])* $id:literal, async fn $name:ident($pool:ident : &$pool_ty:ty) $body:block) => {
        $crate::migration!(@internal $(#[$attr])* $id, $name, $pool, $body);
    };
    (@internal $(#[$attr:meta])* $id:literal, $name:ident, $pool:ident, $body:block) => {
        $(#[$attr])*
        #[doc = ""]
        #[doc = concat!("**Migration ID:** `", $id, "`")]
        #[doc = ""]
        #[doc = "To re-run this migration, delete its tracking row:"]
        #[doc = concat!("```sql\nDELETE FROM _cadmus_migrations WHERE id = '", $id, "';\n```")]
        #[cfg_attr(feature = "tracing", tracing::instrument(skip($pool), fields(migration_id = $id)))]
        async fn $name($pool: &::sqlx::SqlitePool) -> ::std::result::Result<(), ::anyhow::Error> {
            $body
        }

        /// Module generated by the [`crate::migration!`] macro.
        #[allow(non_snake_case)]
        pub mod $name {
            $(#[$attr])*
            #[doc = ""]
            #[doc = concat!("**Migration ID:** `", $id, "`")]
            #[doc = ""]
            #[doc = "To re-run this migration, delete its tracking row:"]
            #[doc = concat!("```sql\nDELETE FROM _cadmus_migrations WHERE id = '", $id, "';\n```")]
            /// The stable ID used to track this migration in `_cadmus_migrations`.
            #[allow(dead_code)]
            pub const MIGRATION_ID: &str = $id;

            #[$crate::ctor::ctor]
            fn __register() {
                fn __boxed(
                    pool: &::sqlx::SqlitePool,
                ) -> ::std::pin::Pin<
                    ::std::boxed::Box<
                        dyn ::std::future::Future<
                            Output = ::std::result::Result<(), ::anyhow::Error>,
                        > + ::std::marker::Send
                        + '_,
                    >,
                > {
                    ::std::boxed::Box::pin(super::$name(pool))
                }
                $crate::db::migrations::register($id, __boxed);
            }
        }
    };
}

#[cfg(feature = "test")]
mod example;

/// Registers a migration function under the given stable `id`.
///
/// # Panics
///
/// Panics if the registry lock is poisoned (should never happen in normal use).
pub fn register(id: &'static str, f: MigrationFn) {
    let mut registry = REGISTRY
        .lock()
        .expect("migration registry lock should not be poisoned");
    registry.insert(id, f);
}

/// Runs all registered migrations that have not yet been executed.
///
/// Reads the `_cadmus_migrations` table to determine which migrations have
/// already run. Executes pending migrations ordered by ID, recording each
/// outcome (`success` or `failed`) before continuing.
///
/// On failure of any individual migration, the error is logged and recorded
/// as `failed` in the tracking table. Execution continues with the remaining
/// migrations so a single failure does not block subsequent independent ones.
pub struct MigrationRunner {
    pool: SqlitePool,
}

impl MigrationRunner {
    pub(super) fn new(pool: SqlitePool) -> Self {
        Self { pool }
    }

    /// Execute all pending registered migrations against the database.
    #[cfg_attr(feature = "tracing", tracing::instrument(skip(self)))]
    pub async fn run_all(&self) -> Result<(), Error> {
        let registry = REGISTRY
            .lock()
            .expect("migration registry lock should not be poisoned")
            .clone();

        if registry.is_empty() {
            return Ok(());
        }

        let already_run: Vec<String> =
            sqlx::query_scalar!("SELECT id FROM _cadmus_migrations WHERE status = 'success'")
                .fetch_all(&self.pool)
                .await?;

        let mut pending: Vec<(&'static str, MigrationFn)> = registry
            .into_iter()
            .filter(|(id, _)| !already_run.contains(&id.to_string()))
            .collect();

        if pending.is_empty() {
            tracing::info!("no pending runtime migrations");
            return Ok(());
        }

        pending.sort_by_key(|(id, _)| *id);

        tracing::info!(count = pending.len(), "running pending runtime migrations");

        for (id, migration_fn) in pending {
            tracing::info!(migration_id = id, "running migration");

            let result = migration_fn(&self.pool).await;
            let status = match &result {
                Ok(_) => "success",
                Err(_) => "failed",
            };

            let executed_at = UnixTimestamp::now();

            sqlx::query!(
                "INSERT INTO _cadmus_migrations (id, executed_at, status) VALUES (?, ?, ?)
                 ON CONFLICT(id) DO UPDATE SET executed_at = excluded.executed_at, status = excluded.status",
                id,
                executed_at,
                status,
            )
            .execute(&self.pool)
            .await?;

            match result {
                Ok(_) => tracing::info!(migration_id = id, "migration succeeded"),
                Err(e) => tracing::error!(migration_id = id, error = %e, "migration failed"),
            }
        }

        Ok(())
    }
}
