files:
  - source: crates/core/i18n/en-GB/*.ftl
    translation: crates/core/i18n/%bcp47_code%/%original_file_name%.ftl
  - source: docs/po/messages.pot
    translation: docs/po/%two_letters_code%.po
