name: Actions lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      workflows: ${{ steps.filter.outputs.workflows }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@d1c1ffe0248fe513906c8e24db8ea791d46f8590 # v3.0.3
        id: filter
        with:
          filters: |
            workflows:
              - '.github/workflows/**'
              - '.github/actions/**'
              - '.github/lint/package.json'

  actionlint:
    needs: changes
    if: needs.changes.outputs.workflows == 'true'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Actionlint
        uses: reviewdog/action-actionlint@v1.72.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: added

  prettier:
    needs: changes
    if: needs.changes.outputs.workflows == 'true'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Prettier
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          prettier_flags: ../.github/workflows/**/*.yml ../.github/actions/**/*.yml
          workdir: .github/lint

  required-actions-lint:
    name: required-actions-lint
    permissions: {}
    needs: [changes, actionlint, prettier]
    if: ${{ always() && (cancelled() || contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::error::One or more required jobs failed or were cancelled"
          exit 1
