name: "Test devenv shell"

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "devenv.nix"
      - "devenv.lock"
      - ".github/workflows/devenv-test.yml"

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      devenv: ${{ steps.filter.outputs.devenv }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@d1c1ffe0248fe513906c8e24db8ea791d46f8590 # v3.0.3
        id: filter
        with:
          filters: |
            devenv:
              - 'devenv.nix'
              - 'devenv.lock'
              - '.github/workflows/devenv-test.yml'

  devenv:
    needs: changes
    if: github.event_name != 'pull_request' || needs.changes.outputs.devenv == 'true'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: "cargo-${{ github.event_name }}-${{ github.event.number || github.ref }}-${{ matrix.os }}"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          submodules: recursive
          persist-credentials: false

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v17
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Test devenv shell builds correctly
        run: devenv shell whoami

  required-devenv:
    name: required-devenv
    permissions: {}
    needs: [changes, devenv]
    if: ${{ always() && github.event_name == 'pull_request' && (cancelled() || contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::error::One or more required jobs failed or were cancelled"
          exit 1
