name: Shell

on:
  pull_request:

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      shell: ${{ steps.filter.outputs.shell }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@d1c1ffe0248fe513906c8e24db8ea791d46f8590 # v3.0.3
        id: filter
        with:
          filters: |
            shell:
              - '**/*.sh'
              - '.github/workflows/shell.yml'

  shellcheck:
    needs: changes
    if: needs.changes.outputs.shell == 'true'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: ShellCheck
        uses: reviewdog/action-shellcheck@v1.32.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: added

  shfmt:
    needs: changes
    if: needs.changes.outputs.shell == 'true'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Shfmt
        uses: reviewdog/action-shfmt@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: added

  required-shell:
    name: required-shell
    permissions: {}
    needs: [changes, shellcheck, shfmt]
    if: ${{ always() && (cancelled() || contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::error::One or more required jobs failed or were cancelled"
          exit 1
